# Scout Mini DUNE 模型训练配置
robot:
  kinematics:  'diff'          # 差速驱动模型
  length: 0.612                # Scout Mini 长度 0.612m + 安全余量
  width: 0.58                 # Scout Mini 宽度 0.58m + 安全余量

# 训练参数
train:
  direct_train: true          # 直接开始训练
  model_name: 'scout_mini_diff'  # 模型保存文件夹名称
  data_size: 100000           # 采样样本数
  data_range: [-10, -10, 10, 10]  # 空间范围
  batch_size: 256             # 批次大小
  epoch: 5000                 # 训练轮数
  valid_freq: 250             # 验证频率
  save_freq: 500              # 保存频率
  lr:  5e-5                    # 学习率
  lr_decay: 0.5               # 学习率衰减
  decay_freq: 1500            # 衰减频率